<?php

namespace AppBundle\Repository;

/**
 * BewerbungenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BewerbungenRepository extends \Doctrine\ORM\EntityRepository
{
}
