<?php

namespace AppBundle\Repository;

/**
 * KarriereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KarriereRepository extends \Doctrine\ORM\EntityRepository
{
}
