<?php

namespace AppBundle\Repository;

/**
 * KontaktRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KontaktRepository extends \Doctrine\ORM\EntityRepository
{
}
