<?php

namespace AppBundle\Repository;

/**
 * StellenangeboteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StellenangeboteRepository extends \Doctrine\ORM\EntityRepository
{
}
