<?php

namespace AppBundle\Repository;

/**
 * toDoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToDoRepository extends \Doctrine\ORM\EntityRepository
{
}
