app:
    resource: '@AppBundle/Controller/'
    type: annotation

# Frontend der Anwendung im WebseitenController definiert!

Startseite:
    path:     /
    defaults: { _controller: AppBundle:Webseiten:startseite }

Konzept:
    path:     /konzept
    defaults: { _controller: AppBundle:Webseiten:konzept }

Leitbild:
    path:     /leitbild
    defaults: { _controller: AppBundle:Webseiten:leitbild }

Kita:
    path:     /kita
    defaults: { _controller: AppBundle:Webseiten:kita }

Kontakt:
    path:     /kontakt
    defaults: { _controller: AppBundle:Webseiten:kontakt }

Anmelden:
    path:     /anmelden
    defaults: { _controller: AppBundle:Webseiten:anmelden }

# Unterseiten im Footer

Karriere:
    path:     /karriere
    defaults: { _controller: AppBundle:Webseiten:karriere}

AGB:
    path:     /agb
    defaults: { _controller: AppBundle:Webseiten:agb}

Impressum:
    path:     /impressum
    defaults: { _controller: AppBundle:Webseiten:impressum}

# Stellenangebote im Dashboard bei Mitarbeiter

Stellenangebote_anzeigen:
    path:     /dashboard/stellenangebot
    defaults: { _controller: AppBundle:Stellenangebote:anzeigen}

Stellenangebote_erstellen:
    path:     /dashboard/stellenangebot/erstellen
    defaults: { _controller: AppBundle:Stellenangebote:erstellen}

Stellenangebote_bearbeiten:
    path:     /dashboard/stellenangebot/bearbeiten/{id}
    defaults: { _controller: AppBundle:Stellenangebote:bearbeiten }

Stellenangebote_details:
    path:     /dashboard/stellenangebot/details/{id}
    defaults: { _controller: AppBundle:Stellenangebote:details }

Stellenangebote_anzeigenfrontend:
    path:     /karriere/stellenangebote
    defaults: { _controller: AppBundle:Stellenangebote:anzeigenfrontend }


Stellenangebote_löschen:
    path:     /dashboard/stellenangebot/löschen/{id}
    defaults: { _controller: AppBundle:Stellenangebote:löschen }

# Backend der Anwendung definiert!

Dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:Webseiten:dashboard }

# Anmeldebereich! Teststatus

Anmelden:
    path:     /anmelden
    defaults: { _controller: AppBundle:security:anmelden }

# Newsseite zum Üben, warten auf Sven´s Aufgaben! Funktioniert!

News_anzeigen:
    path:     /dashboard/news
    defaults: { _controller: AppBundle:News:anzeigen }

News_erstellen:
    path:     /dashboard/news/erstellen
    defaults: { _controller: AppBundle:News:erstellen }

#Mitarbeiter

Mitarbeiter_anzeigen:
    path:     /dashboard/mitarbeiter
    defaults: { _controller: AppBundle:Mitarbeiter:anzeigen }

Mitarbeiter_erstellen:
    path:     /dashboard/mitarbeiter/erstellen
    defaults: { _controller: AppBundle:Mitarbeiter:erstellen }

Mitarbeiter_bearbeiten:
    path:     /dashboard/mitarbeiter/bearbeiten/{id}
    defaults: { _controller: AppBundle:Mitarbeiter:bearbeiten }

Mitarbeiter_details:
    path:     /dashboard/mitarbeiter/details/{id}
    defaults: { _controller: AppBundle:Mitarbeiter:details }

Mitarbeiter_löschen:
    path:     /dashboard/mitarbeiter/löschen/{id}
    defaults: { _controller: AppBundle:Mitarbeiter:löschen }

# Todo

Todos_anzeigen:
    path:     /dashboard/todos
    defaults: { _controller: AppBundle:Todo:anzeigen }

Todos_erstellen:
    path:     /dashboard/todos/erstellen
    defaults: { _controller: AppBundle:Todo:erstellen }

Todos_bearbeiten:
    path:     /dashboard/todos/bearbeiten/{id}
    defaults: { _controller: AppBundle:Todo:bearbeiten }

Todos_details:
    path:     /dashboard/todos/details/{id}
    defaults: { _controller: AppBundle:Todo:details }

Todos_löschen:
    path:     /dashboard/todos/löschen/{id}
    defaults: { _controller: AppBundle:Todo:löschen }

# Finanzen

Finanzen_anzeigen:
    path:     /dashboard/finanzen
    defaults: { _controller: AppBundle:Finanzen:anzeigen }

# Projekt

Projekt_anzeigen:
    path:     /dashboard/projekt
    defaults: { _controller: AppBundle:Projekt:anzeigen}

# Kunden

Kunden_anzeigen:
    path:     /dashboard/kunden
    defaults: { _controller: AppBundle:Kunden:anzeigen}

 # Wiki

Wiki_anzeigen:
    path:     /dashboard/wiki
    defaults: { _controller: AppBundle:Wiki:anzeigen}



