app:
    resource: '@AppBundle/Controller/'
    type: annotation

# Frontend der Anwendung im WebseitenController definiert!

Startseite:
    path:     /
    defaults: { _controller: AppBundle:Webseiten:startseite }

Leitbild:
    path:     /leitbild
    defaults: { _controller: AppBundle:Webseiten:leitbild }

Konzept:
    path:     /konzept
    defaults: { _controller: AppBundle:Webseiten:konzept }

Werte:
    path:     /unsereWerte
    defaults: { _controller: AppBundle:Webseiten:werte }

Kiuweug:
    path:     /kiuweug
    defaults: { _controller: AppBundle:Webseiten:kiuweug }

Kiuweberlin:
    path:     /kiuweberlin
    defaults: { _controller: AppBundle:Webseiten:kiuweberlin }

Kiuwebrandenburg:
    path:     /kiuwebrandenburg
    defaults: { _controller: AppBundle:Webseiten:kiuwebrandenburg }

# Unterseiten im Footer

Impressum:
    path:     /impressum
    defaults: { _controller: AppBundle:Webseiten:impressum}

Kontakt:
    path:     /kontakt
    defaults: { _controller: AppBundle:Kontakt:erstellen}

Karriere:
    path:     /karriere
    defaults: { _controller: AppBundle:Stellenangebote:karriere}

# Backend der Anwendung definiert!

Dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:Dashboard:anzeigen }

# Kontakt im Dashboard bei Kotaktformular

Kontakt_anzeigen:
    path:     /dashboard/kontaktformular
    defaults: { _controller: AppBundle:Kontakt:anzeigen}

Kontakt_löschen:
    path:     /dashboard/kontaktformular/löschen/{id}
    defaults: { _controller: AppBundle:Kontakt:löschen}

# Bewerbungen im Dashboard bei Bewerbern

Bewerbungen_erstellen:
    path:     /karriere/bewerbung
    defaults: { _controller: AppBundle:Bewerbungen:erstellen}

Bewerbungen_anzeigen:
    path:     /dashboard/bewerbungen
    defaults: { _controller: AppBundle:Bewerbungen:anzeigen}

Bewerbungen_details:
    path:     /dashboard/bewerbungen
    defaults: { _controller: AppBundle:Bewerbungen:details}

# Stellenangebote im Dashboard bei Mitarbeiter

Stellenangebote_anzeigen:
    path:     /dashboard/stellenangebot
    defaults: { _controller: AppBundle:Stellenangebote:anzeigen}

Stellenangebote_erstellen:
    path:     /dashboard/stellenangebot/erstellen
    defaults: { _controller: AppBundle:Stellenangebote:erstellen}

Stellenangebote_bearbeiten:
    path:     /dashboard/stellenangebot/bearbeiten/{id}
    defaults: { _controller: AppBundle:Stellenangebote:bearbeiten }

Stellenangebote_details:
    path:     /dashboard/stellenangebot/details/{id}
    defaults: { _controller: AppBundle:Stellenangebote:details }

Stellenangebote_löschen:
    path:     /dashboard/stellenangebot/löschen/{id}
    defaults: { _controller: AppBundle:Stellenangebote:löschen }

 # FOS User Bundle

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"




